name: Infer#

on:
  push:
  pull_request:
  schedule:
    # To more easily compare CodeQL and Infer# results.
    - cron: '30 23 * * 0'
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet build --output binaries-for-infer

      - name: Run Infer#
        uses: microsoft/infersharpaction@v1.5
        id: runinfersharp
        with:
          binary-path: binaries-for-infer

      - name: Upload SARIF output to GitHub Security Center
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: infer-out/report.sarif

      - name: Infer# analysis results
        run: |
          cat <<'EOF'
          ${{ steps.runinfersharp.outputs.results }}
          EOF

      - name: Upload Infer# report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: infer-out/report.txt
